on:
  workflow_dispatch:
    inputs:
      parent:
        type: choice
        description: Parent folder
        options: 
        - parent_1
        - parent_2
      folder:
        required: true

jobs:
  create-setting:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - uses: actions/github-script@v6
      env: 
        USERNAME: ${{ github.actor }}
      with:
        script: |
          const { USERNAME } = process.env
          const response = await github.rest.users.getByUsername({username: USERNAME})
          const { data } = response
          core.exportVariable('FULLNAME', data.name);
    - name: Create setting
      run: bash scripts/create_file_from_template.sh -p ${{ github.event.inputs.parent }} -f ${{ github.event.inputs.folder }}
    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        default_author: github_actor
        message: "Created new settings in ${{ github.event.inputs.parent }}/${{ github.event.inputs.folder }}"
        push: true
