on:
  workflow_dispatch:
    inputs:
      parent:
        type: choice
        description: Parent folder
        options: 
        - parent_1
        - parent_2
      folder:
        required: true

jobs:
  create-setting:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Create setting
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        bash scripts/create_file_from_template.sh -p ${{ github.event.inputs.parent }} -f ${{ github.event.inputs.folder }}
    - uses: actions/github-script@v6
      env: 
        USERNAME: ${{ github.actor }}
      with:
        script: |
          const { USERNAME } = process.env
          const user_info = github.rest.users.getByUsername(USERNAME)
          console.log(user_info)
    - name: Commit and push changes
      run: |
        git config --global user.name ${{ github.actor }}

        git add -A
        git commit -m "Created new settings in ${{ github.event.inputs.parent }}/${{ github.event.inputs.folder }}"
        git push
